/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.generadorqr;

import com.google.zxing.BarcodeFormat;
import com.google.zxing.EncodeHintType;
import com.google.zxing.MultiFormatWriter;
import com.google.zxing.client.j2se.MatrixToImageWriter;
import com.google.zxing.common.BitMatrix;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import org.jdesktop.swingx.prompt.PromptSupport;

/**
 *
 * @author angel
 */
public class QRgui extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(QRgui.class.getName());

    /**
     * Creates new form QRgui
     */
    public QRgui() {
        initComponents();
        setLocationRelativeTo(null);
        checkweb.setSelected(true);
        initPrompt();
        setWindowIcon();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtMensaje = new javax.swing.JTextArea();
        labelMensaje = new javax.swing.JLabel();
        bntCrear = new javax.swing.JButton();
        checkweb = new javax.swing.JRadioButton();
        checkwhatsapp = new javax.swing.JRadioButton();
        acerca = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("QR");
        setAlwaysOnTop(true);
        setResizable(false);

        txtMensaje.setColumns(20);
        txtMensaje.setLineWrap(true);
        txtMensaje.setRows(5);
        txtMensaje.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMensajeKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(txtMensaje);

        labelMensaje.setText("Insertar Mensaje");

        bntCrear.setText("CREAR");
        bntCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntCrearActionPerformed(evt);
            }
        });

        checkweb.setText("Paginas Web");
        checkweb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkwebActionPerformed(evt);
            }
        });

        checkwhatsapp.setText("Whatsapp");
        checkwhatsapp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkwhatsappActionPerformed(evt);
            }
        });

        acerca.setText("Acerca");
        acerca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                acercaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(acerca, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(bntCrear))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(checkweb, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(checkwhatsapp, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelMensaje)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkweb)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkwhatsapp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bntCrear)
                    .addComponent(acerca))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bntCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntCrearActionPerformed
        // TODO add your handling code here:
        String input = txtMensaje.getText().trim();
    if (input.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Ingresa el enlace o número según el tipo seleccionado.", "Generador QR", JOptionPane.WARNING_MESSAGE);
        return;
    }

    try {
        if (checkweb.isSelected()) {
            generarQRParaWeb(input);
            return;
        }
        if (checkwhatsapp.isSelected()) {
            generarQRParaWhatsApp(input);
            return;
        }

        // Caso improbable: ninguno seleccionado
        JOptionPane.showMessageDialog(this, "Selecciona una opción (Páginas Web o WhatsApp).", "Generador QR", JOptionPane.WARNING_MESSAGE);

    } catch (Exception ex) {
        logger.log(java.util.logging.Level.SEVERE, "Error en acción CREAR", ex);
        JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage(), "Generador QR", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_bntCrearActionPerformed

    private void checkwhatsappActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkwhatsappActionPerformed
        // TODO add your handling code here:
        if(checkwhatsapp.isSelected())
            checkweb.setSelected(false);
        else
            checkweb.setSelected(true);
        updatePrompt(true);
    }//GEN-LAST:event_checkwhatsappActionPerformed

    private void checkwebActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkwebActionPerformed
        // TODO add your handling code here:
        if(checkweb.isSelected())
            checkwhatsapp.setSelected(false);
        else
            checkwhatsapp.setSelected(true);
        updatePrompt(true);
    }//GEN-LAST:event_checkwebActionPerformed

    private void txtMensajeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMensajeKeyTyped
        // TODO add your handling code here:
        String x = txtMensaje.getText();
        if(x.isEmpty())
            updatePrompt(true);
        else
            updatePrompt(false);
    }//GEN-LAST:event_txtMensajeKeyTyped

    private void acercaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_acercaMouseClicked
        // TODO add your handling code here:
        mostrarInfo("""
                    Hermano de la iglesia IPUE salamanca 
                    Nombre: Angel Valecillos 
                    Rol: Desarrollador Java 
                    Contacto: +58 678 706 285
                    angel.valecillos1981@gmail.com
                    Redes: 
                    LinkedIn (www.linkedin.com/in/angel-eduardo-valecillos-ab4b5b57), 
                    GitHub (github.com/angelvalecillos), 
                    YouTube (www.youtube.com/@iCantStayStill) 
                    ""","Sobre el Programador");
    }//GEN-LAST:event_acercaMouseClicked

    /**
     * @param args the command line arguments
     */

    // Web (YouTube o cualquier URL http/https)
private void generarQRParaWeb(String url) {
    print("generadorQRParaWeb");
    if (!isValidHttpUrl(url)) {
        JOptionPane.showMessageDialog(this, "La URL debe comenzar con http:// o https://", "Generador QR", JOptionPane.WARNING_MESSAGE);
        return;
    }
    generarYMostrarQR(url);
}

// WhatsApp (grupo por enlace de invitación o chat directo con número)
private void generarQRParaWhatsApp(String input) {
    print("generarQRParaWhatsApp");
    // Caso 1: enlace de invitación a grupo
    if (isValidWhatsAppGroupUrl(input)) {
        generarYMostrarQR(input);
        return;
    }
    // Caso 2: número -> construir wa.me para chat directo
    if (isProbablePhoneNumber(input)) {
        String wa = buildWaMeUrlFromNumber(input);
        int r = JOptionPane.showConfirmDialog(
                this,
                "No parece un enlace de grupo.\n¿Crear QR para chat directo con: " + wa + " ?",
                "WhatsApp", JOptionPane.YES_NO_OPTION
        );
        if (r == JOptionPane.YES_OPTION) {
            generarYMostrarQR(wa);
        }
        return;
    }

    JOptionPane.showMessageDialog(
            this,
            "Para grupo usa el enlace de invitación: https://chat.whatsapp.com/<codigo>\n" +
            "Para chat directo, ingresa un número (se construirá https://wa.me/<numero>).",
            "WhatsApp", JOptionPane.WARNING_MESSAGE
    );
}
    
    // URL http/https genérica
private boolean isValidHttpUrl(String s) {
    print("isValidHttpUrl");
    try {
        java.net.URL u = new java.net.URL(s);
        u.toURI();
        String p = u.getProtocol();
        return "http".equalsIgnoreCase(p) || "https".equalsIgnoreCase(p);
    } catch (Exception e) {
        return false;
    }
}

// Enlace de invitación a grupo de WhatsApp: https://chat.whatsapp.com/<codigo>
private boolean isValidWhatsAppGroupUrl(String s) {
    print("isValidWhatsAppGroupUrl");
    try {
        java.net.URL u = new java.net.URL(s);
        if (!"https".equalsIgnoreCase(u.getProtocol())) return false;
        if (!"chat.whatsapp.com".equalsIgnoreCase(u.getHost())) return false;
        String path = u.getPath(); // e.g. "/AbC123xyz..."
        // Códigos típicos son alfanuméricos, ~22 caracteres. Aceptamos 10-32 para ser tolerantes.
        return path != null && path.matches("/[A-Za-z0-9]{10,32}");
    } catch (Exception e) {
        return false;
    }
}

// ¿Parece un número en formato internacional (E.164 sin signos)?
    private boolean isProbablePhoneNumber(String s) {
        print("isProbablePhoneNumber");
    String digits = s.replaceAll("\\D", "");
    // Longitud razonable internacional: 8 a 15 dígitos
    return digits.length() >= 8 && digits.length() <= 15;
}

    // Construir enlace wa.me desde número (quita signos y +)
    private String buildWaMeUrlFromNumber(String s) {
        print("buildWaMeUrlFromNumber");
    String digits = s.replaceAll("\\D", "");
    return "https://wa.me/" + digits;
}
    
    private void generarYMostrarQR(String contenido) {
        print("generarYMostrarQR");
    try {
        int size = 300;
        java.util.Map<com.google.zxing.EncodeHintType, Object> hints = new java.util.HashMap<>();
        hints.put(EncodeHintType.CHARACTER_SET, "UTF-8");
        hints.put(EncodeHintType.MARGIN, 1);
        hints.put(EncodeHintType.ERROR_CORRECTION, com.google.zxing.qrcode.decoder.ErrorCorrectionLevel.M);
        BitMatrix matrix = new MultiFormatWriter()
                .encode(contenido, BarcodeFormat.QR_CODE, size, size, hints);

        java.awt.image.BufferedImage image = MatrixToImageWriter.toBufferedImage(matrix);

        JOptionPane.showMessageDialog(
                this,
                new JLabel(new ImageIcon(image)),
                "QR generado",
                JOptionPane.PLAIN_MESSAGE
        );
    } catch (Exception ex) {
        logger.log(java.util.logging.Level.SEVERE, "Error generando QR", ex);
        JOptionPane.showMessageDialog(this, "Error al generar el QR: " + ex.getMessage(), "Generador QR", JOptionPane.ERROR_MESSAGE);
    }
}

    private void initPrompt() {
        print("initPrompt");
    PromptSupport.setForeground(java.awt.Color.GRAY, txtMensaje);
    PromptSupport.setFocusBehavior(PromptSupport.FocusBehavior.SHOW_PROMPT, txtMensaje);
    updatePrompt(true);
}

    private void updatePrompt(boolean x) {
        print("updatePrompt");
    if (checkweb.isSelected()&& x) {
        PromptSupport.setPrompt("Ejemplo: \n https://www.youtube.com/@TuCanal \n o https://tuweb.com", txtMensaje);
    } else if (checkwhatsapp.isSelected() && x) {
        PromptSupport.setPrompt("Grupo: \n https://chat.whatsapp.com/CODIGO  \n  Chat directo: 34XXXXXXXXXX", txtMensaje);
    }
    else if (!x)
        PromptSupport.setPrompt("", txtMensaje);
    
}
    
    private void setWindowIcon() {
        print("setWindowIcon");
    try {
        java.util.List<java.awt.Image> icons = new java.util.ArrayList<>();
        java.net.URL i16 = getClass().getResource("/icons/QR.JPG");
        java.net.URL i32 = getClass().getResource("/icons/QR.JPG");
        java.net.URL i64 = getClass().getResource("/icons/QR.JPG");

        if (i16 != null) icons.add(javax.imageio.ImageIO.read(i16));
        if (i32 != null) icons.add(javax.imageio.ImageIO.read(i32));
        if (i64 != null) icons.add(javax.imageio.ImageIO.read(i64));

        if (!icons.isEmpty()) {
            // Permite que el SO elija el mejor tamaño
            setIconImages(icons);
        } else {
            logger.warning("No se encontraron iconos en /icons/");
        }
    } catch (Exception ex) {
        logger.log(java.util.logging.Level.WARNING, "No se pudo establecer el icono de la ventana", ex);
    }
}
    
    // Cargar un icono desde resources (src/main/resources/icons/app-qr-32.png)
    private javax.swing.Icon getAppIcon() {
        print("getAppIcon");
    java.net.URL url = getClass().getResource("/icons/icon.png");
    return (url != null) ? new javax.swing.ImageIcon(url) : null;
}

// Mensaje informativo con icono personalizado
    private void mostrarInfo(String mensaje, String titulo) {
        print("mostrarInfo");
    javax.swing.Icon icon = getAppIcon();
    // showMessageDialog con icono propio
    javax.swing.JOptionPane.showMessageDialog(
        this,
        mensaje,
        titulo != null ? titulo : "Información",
        javax.swing.JOptionPane.INFORMATION_MESSAGE,
        icon
    );
}
    
    private void print(String x){
        System.out.println("QRgui = "+x);
    }
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new QRgui().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel acerca;
    private javax.swing.JButton bntCrear;
    private javax.swing.JRadioButton checkweb;
    private javax.swing.JRadioButton checkwhatsapp;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelMensaje;
    private javax.swing.JTextArea txtMensaje;
    // End of variables declaration//GEN-END:variables
}
